// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TreesAndRays.Data;

#nullable disable

namespace TreesAndRays.Migrations
{
    [DbContext(typeof(dbContext))]
    [Migration("20240501092721_sensordata")]
    partial class sensordata
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("TreesAndRays.Data.SensorsData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("HumidityPercentage")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Moisture")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("MoisturePercentage")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TempCelsius")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TempFahrenheit")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("SensorsData");
                });
#pragma warning restore 612, 618
        }
    }
}
